import type { EntityConfig } from './types';

const STATUS_OPTIONS = [
  { value: 'draft', label: 'Borrador' },
  { value: 'published', label: 'Publicado' },
  { value: 'archived', label: 'Archivado' },
];

const seo = (): EntityConfig['fields'] => [
  { name: 'meta_title', label: 'SEO · Título', type: 'i18n-text', group: 'SEO' },
  { name: 'meta_description', label: 'SEO · Descripción', type: 'i18n-textarea', group: 'SEO' },
];

const publishFields = (): EntityConfig['fields'] => [
  { name: 'status', label: 'Estado', type: 'select', options: STATUS_OPTIONS, group: 'Publicación', required: true },
  { name: 'featured', label: 'Destacado', type: 'boolean', group: 'Publicación' },
  { name: 'sort_order', label: 'Orden', type: 'number', group: 'Publicación' },
];

export const ENTITIES: Record<string, EntityConfig> = {
  destinations: {
    key: 'destinations',
    table: 'destinations',
    labelSingular: 'Destino',
    labelPlural: 'Destinos',
    icon: 'MapPin',
    titleField: 'name',
    listColumns: [
      { field: 'name', label: 'Nombre', kind: 'i18n' },
      { field: 'region', label: 'Región', kind: 'text' },
      { field: 'status', label: 'Estado', kind: 'status' },
      { field: 'featured', label: 'Destacado', kind: 'bool' },
    ],
    images: { table: 'destination_images', fk: 'destination_id' },
    fields: [
      { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'General' },
      { name: 'name', label: 'Nombre', type: 'i18n-text', required: true, group: 'General' },
      { name: 'tagline', label: 'Frase corta', type: 'i18n-text', group: 'General' },
      { name: 'description', label: 'Descripción', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'best_time', label: 'Mejor época', type: 'i18n-text', group: 'General' },
      { name: 'highlights', label: 'Destacados (uno por línea)', type: 'i18n-list', group: 'General', colSpan: 2 },
      { name: 'region', label: 'Región', type: 'text', group: 'Ubicación' },
      { name: 'country', label: 'País', type: 'text', group: 'Ubicación' },
      { name: 'latitude', label: 'Latitud', type: 'number', group: 'Ubicación' },
      { name: 'longitude', label: 'Longitud', type: 'number', group: 'Ubicación' },
      ...publishFields(),
      ...seo(),
    ],
    defaults: { country: 'Colombia', status: 'draft' },
  },

  accommodations: {
    key: 'accommodations',
    table: 'accommodations',
    labelSingular: 'Hospedaje',
    labelPlural: 'Hospedajes',
    icon: 'BedDouble',
    titleField: 'name',
    listColumns: [
      { field: 'name', label: 'Nombre', kind: 'i18n' },
      { field: 'city', label: 'Ciudad', kind: 'text' },
      { field: 'price_from', label: 'Desde', kind: 'money' },
      { field: 'status', label: 'Estado', kind: 'status' },
      { field: 'featured', label: 'Destacado', kind: 'bool' },
    ],
    images: { table: 'accommodation_images', fk: 'accommodation_id' },
    fields: [
      { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'General' },
      { name: 'name', label: 'Nombre', type: 'i18n-text', required: true, group: 'General' },
      {
        name: 'type', label: 'Tipo', type: 'select', group: 'General', options: [
          { value: 'hotel', label: 'Hotel' },
          { value: 'apartment', label: 'Apartamento' },
          { value: 'house', label: 'Casa' },
          { value: 'cabin', label: 'Cabaña' },
          { value: 'hostel', label: 'Hostal' },
          { value: 'glamping', label: 'Glamping' },
          { value: 'finca', label: 'Finca' },
        ],
      },
      { name: 'summary', label: 'Resumen', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'description', label: 'Descripción', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'location_note', label: 'Nota de ubicación', type: 'i18n-text', group: 'General', colSpan: 2 },
      { name: 'destination_id', label: 'Destino', type: 'ref', refTable: 'destinations', group: 'Ubicación' },
      { name: 'city', label: 'Ciudad', type: 'text', group: 'Ubicación' },
      { name: 'region', label: 'Región', type: 'text', group: 'Ubicación' },
      { name: 'address', label: 'Dirección', type: 'text', group: 'Ubicación', colSpan: 2 },
      { name: 'latitude', label: 'Latitud', type: 'number', group: 'Ubicación' },
      { name: 'longitude', label: 'Longitud', type: 'number', group: 'Ubicación' },
      { name: 'price_from', label: 'Precio desde', type: 'number', group: 'Precio y capacidad' },
      { name: 'currency', label: 'Moneda', type: 'text', group: 'Precio y capacidad' },
      { name: 'max_guests', label: 'Huéspedes máx.', type: 'number', group: 'Precio y capacidad' },
      { name: 'bedrooms', label: 'Habitaciones', type: 'number', group: 'Precio y capacidad' },
      { name: 'beds', label: 'Camas', type: 'number', group: 'Precio y capacidad' },
      { name: 'bathrooms', label: 'Baños', type: 'number', group: 'Precio y capacidad' },
      { name: 'check_in_time', label: 'Check-in', type: 'text', group: 'Precio y capacidad' },
      { name: 'check_out_time', label: 'Check-out', type: 'text', group: 'Precio y capacidad' },
      { name: 'external_booking_url', label: 'URL de reserva externa', type: 'text', group: 'Enlaces', colSpan: 2 },
      {
        name: 'external_platform', label: 'Plataforma', type: 'select', group: 'Enlaces', options: [
          { value: '', label: '—' },
          { value: 'booking', label: 'Booking' },
          { value: 'airbnb', label: 'Airbnb' },
          { value: 'direct', label: 'Directo' },
          { value: 'other', label: 'Otra' },
        ],
      },
      ...publishFields(),
      ...seo(),
    ],
    defaults: { country: 'Colombia', currency: 'COP', type: 'hotel', status: 'draft' },
  },

  tours: {
    key: 'tours',
    table: 'tours',
    labelSingular: 'Tour',
    labelPlural: 'Tours',
    icon: 'Compass',
    titleField: 'name',
    listColumns: [
      { field: 'name', label: 'Nombre', kind: 'i18n' },
      { field: 'city', label: 'Ciudad', kind: 'text' },
      { field: 'price_from', label: 'Desde', kind: 'money' },
      { field: 'status', label: 'Estado', kind: 'status' },
      { field: 'featured', label: 'Destacado', kind: 'bool' },
    ],
    images: { table: 'tour_images', fk: 'tour_id' },
    fields: [
      { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'General' },
      { name: 'name', label: 'Nombre', type: 'i18n-text', required: true, group: 'General' },
      { name: 'summary', label: 'Resumen', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'description', label: 'Descripción', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'itinerary', label: 'Itinerario', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'excluded', label: 'No incluye (uno por línea)', type: 'i18n-list', group: 'General', colSpan: 2 },
      { name: 'destination_id', label: 'Destino', type: 'ref', refTable: 'destinations', group: 'Ubicación' },
      { name: 'city', label: 'Ciudad', type: 'text', group: 'Ubicación' },
      { name: 'region', label: 'Región', type: 'text', group: 'Ubicación' },
      { name: 'category', label: 'Categoría', type: 'text', group: 'Ubicación' },
      { name: 'meeting_point', label: 'Punto de encuentro', type: 'text', group: 'Ubicación', colSpan: 2 },
      { name: 'price_from', label: 'Precio desde', type: 'number', group: 'Detalles' },
      { name: 'currency', label: 'Moneda', type: 'text', group: 'Detalles' },
      { name: 'duration_hours', label: 'Duración (horas)', type: 'number', group: 'Detalles' },
      { name: 'duration_label', label: 'Duración (texto)', type: 'i18n-text', group: 'Detalles' },
      { name: 'schedule_label', label: 'Horario (texto)', type: 'i18n-text', group: 'Detalles', colSpan: 2 },
      {
        name: 'difficulty', label: 'Dificultad', type: 'select', group: 'Detalles', options: [
          { value: '', label: '—' },
          { value: 'easy', label: 'Fácil' },
          { value: 'moderate', label: 'Moderada' },
          { value: 'hard', label: 'Difícil' },
        ],
      },
      { name: 'min_pax', label: 'Mín. personas', type: 'number', group: 'Detalles' },
      { name: 'max_pax', label: 'Máx. personas', type: 'number', group: 'Detalles' },
      ...publishFields(),
      ...seo(),
    ],
    defaults: { currency: 'COP', status: 'draft' },
  },

  events: {
    key: 'events',
    table: 'events',
    labelSingular: 'Evento',
    labelPlural: 'Eventos',
    icon: 'CalendarDays',
    titleField: 'name',
    listColumns: [
      { field: 'name', label: 'Nombre', kind: 'i18n' },
      { field: 'city', label: 'Ciudad', kind: 'text' },
      { field: 'start_date', label: 'Inicio', kind: 'text' },
      { field: 'status', label: 'Estado', kind: 'status' },
      { field: 'featured', label: 'Destacado', kind: 'bool' },
    ],
    images: { table: 'event_images', fk: 'event_id' },
    fields: [
      { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'General' },
      { name: 'name', label: 'Nombre', type: 'i18n-text', required: true, group: 'General' },
      { name: 'description', label: 'Descripción', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'month_label', label: 'Mes (texto)', type: 'i18n-text', group: 'General' },
      { name: 'destination_id', label: 'Destino', type: 'ref', refTable: 'destinations', group: 'Ubicación' },
      { name: 'city', label: 'Ciudad', type: 'text', group: 'Ubicación' },
      { name: 'region', label: 'Región', type: 'text', group: 'Ubicación' },
      { name: 'venue', label: 'Lugar / sede', type: 'text', group: 'Ubicación', colSpan: 2 },
      { name: 'start_date', label: 'Fecha inicio', type: 'date', group: 'Fechas' },
      { name: 'end_date', label: 'Fecha fin', type: 'date', group: 'Fechas' },
      { name: 'is_recurring', label: 'Recurrente', type: 'boolean', group: 'Fechas' },
      { name: 'ticket_url', label: 'URL de entradas', type: 'text', group: 'Enlaces', colSpan: 2 },
      { name: 'price_from', label: 'Precio desde', type: 'number', group: 'Enlaces' },
      { name: 'currency', label: 'Moneda', type: 'text', group: 'Enlaces' },
      ...publishFields(),
      ...seo(),
    ],
    defaults: { currency: 'COP', status: 'draft' },
  },

  real_estate_listings: {
    key: 'real_estate_listings',
    table: 'real_estate_listings',
    labelSingular: 'Propiedad en venta',
    labelPlural: 'Propiedades a la venta',
    icon: 'Home',
    titleField: 'title',
    listColumns: [
      { field: 'title', label: 'Título', kind: 'i18n' },
      { field: 'city', label: 'Ciudad', kind: 'text' },
      { field: 'price', label: 'Precio', kind: 'money' },
      { field: 'status', label: 'Estado', kind: 'status' },
      { field: 'featured', label: 'Destacado', kind: 'bool' },
    ],
    images: { table: 'real_estate_listing_images', fk: 'listing_id' },
    fields: [
      { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'General' },
      { name: 'reference_code', label: 'Código interno', type: 'text', group: 'General' },
      { name: 'title', label: 'Título', type: 'i18n-text', required: true, group: 'General' },
      { name: 'description', label: 'Descripción', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      {
        name: 'operation', label: 'Operación', type: 'select', group: 'General', options: [
          { value: 'sale', label: 'Venta' },
          { value: 'rent', label: 'Arriendo' },
        ],
      },
      {
        name: 'property_type', label: 'Tipo', type: 'select', group: 'General', options: [
          { value: 'apartment', label: 'Apartamento' },
          { value: 'house', label: 'Casa' },
          { value: 'lot', label: 'Lote' },
          { value: 'farm', label: 'Finca' },
          { value: 'commercial', label: 'Local comercial' },
          { value: 'office', label: 'Oficina' },
          { value: 'building', label: 'Edificio' },
        ],
      },
      {
        name: 'availability', label: 'Disponibilidad', type: 'select', group: 'General', options: [
          { value: 'available', label: 'Disponible' },
          { value: 'reserved', label: 'Reservada' },
          { value: 'sold', label: 'Vendida' },
          { value: 'rented', label: 'Arrendada' },
        ],
      },
      { name: 'destination_id', label: 'Destino', type: 'ref', refTable: 'destinations', group: 'Ubicación' },
      { name: 'city', label: 'Ciudad', type: 'text', group: 'Ubicación' },
      { name: 'region', label: 'Región', type: 'text', group: 'Ubicación' },
      { name: 'neighborhood', label: 'Barrio', type: 'text', group: 'Ubicación' },
      { name: 'address', label: 'Dirección (privada)', type: 'text', group: 'Ubicación', colSpan: 2 },
      { name: 'price', label: 'Precio', type: 'number', group: 'Precio' },
      { name: 'currency', label: 'Moneda', type: 'text', group: 'Precio' },
      { name: 'hoa_fee', label: 'Administración', type: 'number', group: 'Precio' },
      { name: 'area_total_m2', label: 'Área total (m²)', type: 'number', group: 'Características' },
      { name: 'area_built_m2', label: 'Área construida (m²)', type: 'number', group: 'Características' },
      { name: 'bedrooms', label: 'Alcobas', type: 'number', group: 'Características' },
      { name: 'bathrooms', label: 'Baños', type: 'number', group: 'Características' },
      { name: 'half_bathrooms', label: 'Medios baños', type: 'number', group: 'Características' },
      { name: 'parking_spaces', label: 'Parqueaderos', type: 'number', group: 'Características' },
      { name: 'stratum', label: 'Estrato', type: 'number', group: 'Características' },
      { name: 'floor', label: 'Piso', type: 'number', group: 'Características' },
      { name: 'floors_total', label: 'Pisos totales', type: 'number', group: 'Características' },
      { name: 'year_built', label: 'Año construcción', type: 'number', group: 'Características' },
      { name: 'is_furnished', label: 'Amoblado', type: 'boolean', group: 'Características' },
      { name: 'allows_pets', label: 'Admite mascotas', type: 'boolean', group: 'Características' },
      ...publishFields(),
      ...seo(),
    ],
    defaults: { currency: 'COP', operation: 'sale', property_type: 'apartment', availability: 'available', status: 'draft' },
  },

  testimonials: {
    key: 'testimonials',
    table: 'testimonials',
    labelSingular: 'Testimonio',
    labelPlural: 'Testimonios',
    icon: 'Quote',
    titleField: 'author_name',
    listColumns: [
      { field: 'author_name', label: 'Autor', kind: 'text' },
      { field: 'author_location', label: 'Ubicación', kind: 'text' },
      { field: 'rating', label: 'Rating', kind: 'text' },
      { field: 'status', label: 'Estado', kind: 'status' },
      { field: 'featured', label: 'Destacado', kind: 'bool' },
    ],
    fields: [
      { name: 'author_name', label: 'Nombre del autor', type: 'text', required: true, group: 'General' },
      { name: 'author_location', label: 'Ubicación', type: 'text', group: 'General' },
      { name: 'rating', label: 'Rating (1-5)', type: 'number', group: 'General' },
      { name: 'quote', label: 'Testimonio', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      {
        name: 'source', label: 'Fuente', type: 'select', group: 'General', options: [
          { value: '', label: '—' },
          { value: 'google', label: 'Google' },
          { value: 'whatsapp', label: 'WhatsApp' },
          { value: 'instagram', label: 'Instagram' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'tripadvisor', label: 'TripAdvisor' },
          { value: 'direct', label: 'Directo' },
        ],
      },
      ...publishFields(),
    ],
    defaults: { status: 'draft' },
  },

  blog_posts: {
    key: 'blog_posts',
    table: 'blog_posts',
    labelSingular: 'Artículo',
    labelPlural: 'Blog',
    icon: 'Newspaper',
    titleField: 'title',
    listColumns: [
      { field: 'title', label: 'Título', kind: 'i18n' },
      { field: 'published_at', label: 'Publicado', kind: 'text' },
      { field: 'status', label: 'Estado', kind: 'status' },
      { field: 'featured', label: 'Destacado', kind: 'bool' },
    ],
    fields: [
      { name: 'slug', label: 'Slug', type: 'slug', required: true, group: 'General' },
      { name: 'title', label: 'Título', type: 'i18n-text', required: true, group: 'General' },
      { name: 'category_id', label: 'Categoría', type: 'ref', refTable: 'blog_categories', group: 'General' },
      { name: 'excerpt', label: 'Extracto', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'body', label: 'Cuerpo (Markdown)', type: 'i18n-textarea', group: 'General', colSpan: 2 },
      { name: 'reading_minutes', label: 'Minutos de lectura', type: 'number', group: 'General' },
      { name: 'published_at', label: 'Fecha de publicación', type: 'date', group: 'Publicación' },
      ...publishFields().filter((f) => f.name !== 'sort_order'),
      ...seo(),
    ],
    defaults: { status: 'draft' },
  },
};

export const ENTITY_ORDER: (keyof typeof ENTITIES)[] = [
  'destinations',
  'accommodations',
  'tours',
  'events',
  'real_estate_listings',
  'testimonials',
  'blog_posts',
];
